#!/bin/sh -e

prefix="$(mktemp -d)"
mkdir -p "$prefix/share/dipm"
cp pkgs.ini "$prefix/share/dipm/pkgs.ini"

dipm --prefix "$prefix" install "$@"
dipm --prefix "$prefix" uninstall "$@"
rm -r "$prefix"
