#!/bin/sh

all_pkgs() {
    grep -o '^\s*\[.*\.pkg\]' pkgs.ini | sed -e 's/^\s*\[//' -e 's/\.pkg\]$//'
}

ini_section() {
    section=$1
    awk "/\[.*\]/ {print_it=0} /^\[$section\]$/ {print_it=1} print_it"
}

ini_field() {
    field=$1
    grep "${field}=" | cut -d'=' -f2-
}

check_pkg() {
    pkg=$1

    pkg_section=$(ini_section "$pkg\.pkg" <pkgs.ini)
    update_section=$(ini_section "$pkg\.update" <pkgs.ini)

    version=$(echo "$pkg_section" | ini_field 'version')
    url=$(echo "$update_section" | ini_field 'url')
    find_version_regex=$(echo "$update_section" | ini_field 'find_version_regex')
    extract_version_regex=$(echo "$update_section" | ini_field 'extract_version_regex')

    new_version=$(curl -s "$url" |
        grep -m1 -o "$find_version_regex" |
        grep -m1 -o "$extract_version_regex")

    if [ "$version" != "$new_version" ]; then
        echo "$pkg $version -> $new_version" >&2
    fi
}

check_all() {
    all_pkgs | while read -r pkg; do
        check_pkg "$pkg"
    done
}

case $1 in
    '') check_all ;;
    *) check_pkg "$1" ;;
esac
